# author: steeve LAQUITAINE

proj_path: /Users/steeve_laquitaine/desktop/CodeHub/intent/

annotation: None # 'do', 'load'
sampling:
  random_state: 0
  sample: 100
intent_class: ["card_arrival", "exchange_via_app"]  # good parsing performance

# mlflow tracking parameters  
# - tracking_uri must end with mlruns/  
mlflow:
  experiment_name: unsup_intent_recog
  tracking_uri: file:///Users/steeve_laquitaine/Desktop/CodeHub/intent/intent/mlruns/

# Denoising techniques before functional parsing (intent, intendeed)
# - filter-lcs-with-seed-syntax: longest common subsequence with the SEED syntax
DENOISING:
  SEED: " VB NP"  # the seed syntax for comparison
  FILTERING_METHOD: filter-lcs-with-seed-syntax
DIST_THRES: 3  # inference threshold for clustering, low values -> more clusters

NUM_SENT: 1  # keep query with max one sentence
THRES_SIM_SCORE: 1  # Keep queries syntactically similar to seed
FILT_MOOD: "ask"  # ("state", "wish-or-excl", "ask")  # Keep statements


HCL_METHOD: "average"


PREDICT_METHOD: "cluster_label_mode"
